services:
  nginx:
#    image: nginx:latest
    image: utoptop/nginx-acme:latest
    container_name: nginx
    restart: always
#    network_mode: "host"
    ports:
      - "8006:80"
      - "4446:443"
    volumes:
      - ./certs:/var/cache/nginx/acme-letsencrypt   # 映射证书目录
      - ./nginx:/etc/nginx
      - ./other:/etc/nginx/other
